enableVersioning: true
handle: homepage
name: Homepage
propagationMethod: all
siteSettings:
  f0347675-7c26-4cb8-af05-c4d22401af88:
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
